name: Generate Random Tip JSON

on:
  push:
    branches:
      - master
  schedule:
    - cron: '* * * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-tip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate tip.json
        run: |
          python generate_tip.py

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: public
          clean: true
